name: showpass
description: ShowPass - Premium Ticket App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  sqflite_common_ffi: ^2.3.4
  sqflite: ^2.3.3+1
  path:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^8.1.0
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon_showpass.png"
  remove_alpha_ios: true
